function mkW(w,p,m,s){return{id:Date.now()*1000+Math.floor(Math.random()*1000),word:w.toLowerCase(),phonetic:p||"",meaning:m,sentences:s||[],level:0,interval:0,ease:2.5,reps:0,nextReview:today(),lastReview:null}}
function today(){return new Date().toISOString().split("T")[0]}
function loadWords(){var s=localStorage.getItem("vl_words");if(s)return JSON.parse(s);return BUILTIN.map(function(b){return mkW(b.w,b.p,b.m,b.s)})}
function saveWords(){localStorage.setItem("vl_words",JSON.stringify(words))}
var words=loadWords(),queue=[],qi=0,sentIdx=0,doneToday=0,showingAnswer=false;
function getDue(){return words.filter(function(w){return w.nextReview<=today()})}
function srs(w,rem){if(rem){w.reps+=1;if(w.reps===1)w.interval=1;else if(w.reps===2)w.interval=3;else w.interval=Math.round(w.interval*w.ease);w.ease=Math.max(1.3,w.ease+0.1);w.level=Math.min(2,w.level+1)}else{w.reps=0;w.interval=0;w.ease=Math.max(1.3,w.ease-0.2);w.level=0}var d=new Date();d.setDate(d.getDate()+w.interval);w.nextReview=d.toISOString().split("T")[0];w.lastReview=today();return w}
function escH(s){return s.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;")}
function escJ(s){return s.replace(/\\/g,"\\\\").replace(/'/g,"\\'")}
function escRe(s){return s.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")}
function updateStats(){var due=getDue();document.getElementById("statTotal").textContent=words.length;document.getElementById("statDue").textContent=due.length;document.getElementById("statDone").textContent=doneToday;var b=document.getElementById("reviewBadge");if(due.length>0){b.style.display="flex";b.textContent=due.length}else{b.style.display="none"}updateStreak()}
function updateStreak(){var s=0,base=new Date();for(var i=0;i<365;i++){var d=new Date(base);d.setDate(d.getDate()-i);var ds=d.toISOString().split("T")[0];var log=JSON.parse(localStorage.getItem("vl_log_"+ds)||"[]");if(log.length>0)s++;else if(i>0)break}document.getElementById("streakBadge").textContent="\uD83D\uDD25 "+s+"\u5929"}
function renderCard(){queue=getDue();qi=0;sentIdx=0;showingAnswer=false;document.getElementById("judgeRow").style.display="none";document.getElementById("completeArea").innerHTML="";if(queue.length===0){document.getElementById("cardArea").innerHTML="";document.getElementById("completeArea").innerHTML='<div class="complete fade-up"><div class="em">\uD83C\uDF89</div><h2>\u4ECA\u5929\u641E\u5B9A\u554A\uFF01</h2><p>\u5DF2\u5B8C\u6210 '+doneToday+' \u4E2A\u5355\u8BCD</p><button class="btn-rst" onclick="reviewAll()">\uD83D\uDD04 \u590D\u4E60\u5168\u90E8\u8BCD\u5E93</button></div>';updateProg();return}renderCur()}
function renderCur(){if(qi>=queue.length){renderCard();return}var w=queue[qi],ts=w.sentences.length||1,area=document.getElementById("cardArea");if(!showingAnswer){var blanked=w.sentences[sentIdx]?w.sentences[sentIdx].replace(/\{\{(\w+)\}\}/gi,'<span class="blank">________</span>'):"";var dots="";for(var i=0;i<ts;i++){dots+='<div class="s-dot'+(i===sentIdx?" act":"")+'"></div>'}area.innerHTML='<div class="card fade-up" onclick="flipCard()"><div class="card-deco">?</div><div class="hint-label">\uD83E\uDDE9 \u6839\u636E\u63D0\u793A\u731C\u5355\u8BCD</div><div class="sentence">'+blanked+'</div><div class="hint-box"><div class="hl">\u610F\u5927\u5229\u8BED\u63D0\u793A</div><div class="hm">'+escH(w.meaning)+'</div></div>'+(ts>1?'<div class="sent-nav">'+dots+'<span class="s-nav-label">'+(sentIdx+1)+'/'+ts+' \u4F8B\u53E5</span></div>':'')+'<div class="tap-hint">\uD83D\uDC46 \u70B9\u51FB\u67E5\u770B\u7B54\u6848</div></div>'}else{var filled=w.sentences[sentIdx]?w.sentences[sentIdx].replace(/\{\{(\w+)\}\}/gi,'<span class="filled">$1</span>'):"";var dots2="";for(var j=0;j<ts;j++){dots2+='<div class="s-dot'+(j<=sentIdx?" act":"")+'"></div>'}var nexBtn=sentIdx+1<ts?'<button class="btn-next-sent" onclick="nextSent()">\u770B\u4E0B\u4E00\u4E2A\u4F8B\u53E5 \u2192</button>':"";area.innerHTML='<div class="card fade-up"><button class="speak-btn" onclick="event.stopPropagation();speak(\''+escJ(w.word)+'\')">\uD83D\uDD0A</button><div class="aw">'+escH(w.word)+'</div>'+(w.phonetic?'<div class="aph">'+escH(w.phonetic)+'</div>':'')+'<div class="asent">'+filled+'</div>'+nexBtn+(ts>1?'<div class="sent-nav">'+dots2+'<span class="s-nav-label">'+(sentIdx+1)+'/'+ts+' \u4F8B\u53E5</span></div>':'')+'<div class="amean">\uD83D\uDCD6 '+escH(w.meaning)+'</div></div>'}updateProg()}
function flipCard(){if(!showingAnswer){showingAnswer=true;renderCur();document.getElementById("judgeRow").style.display="flex"}}
function nextSent(){var w=queue[qi];if(sentIdx+1<(w.sentences.length||0)){sentIdx++;renderCur()}}
function updateProg(){var total=Math.max(queue.length,1),pct=Math.round(qi/total*100);document.getElementById("progFill").style.width=pct+"%";document.getElementById("progFrac").textContent=Math.min(qi+1,total)+"/"+total}
function judge(rem){var w=queue[qi],wi=words.findIndex(function(x){return x.id===w.id});if(wi===-1)return;words[wi]=srs(words[wi],rem);saveWords();doneToday++;logToday(w.id);updateStats();var card=document.querySelector(".card");if(card){card.classList.add(rem?"slide-out-l":"slide-out-r");setTimeout(function(){qi++;sentIdx=0;showingAnswer=false;document.getElementById("judgeRow").style.display="none";if(qi>=queue.length)renderCard();else renderCur()},180)}}
function logToday(id){var ds=today();var log=JSON.parse(localStorage.getItem("vl_log_"+ds)||"[]");log.push({id:id});localStorage.setItem("vl_log_"+ds,JSON.stringify(log))}
function reviewAll(){words.forEach(function(w){w.nextReview=today()});saveWords();updateStats();renderCard()}
function goPage(name,btn){document.querySelectorAll(".page").forEach(function(p){p.classList.remove("active")});document.querySelectorAll(".nav-item").forEach(function(b){b.classList.remove("active")});document.getElementById("page"+name.charAt(0).toUpperCase()+name.slice(1)).classList.add("active");if(btn)btn.classList.add("active");if(name==="card")renderCard();if(name==="list")renderList();if(name==="review")renderReview()}
function renderList(){var area=document.getElementById("listArea");if(words.length===0){area.innerHTML='<div class="empty"><div class="ic">\uD83D\uDCED</div>\u8FD8\u6CA1\u6709\u5355\u8BCD\uFF0C\u5FEB\u53BB\u6DFB\u52A0\u5427</div>';return}var h="";words.forEach(function(w){var lv=["<span class=\"wl-lv lv-0\">\u65B0\u8BCD</span>","<span class=\"wl-lv lv-1\">\u5B66\u4E60\u4E2D</span>","<span class=\"wl-lv lv-2\">\u5DF2\u638C\u63E1</span>"][w.level];h+='<div class="wl-item fade-up"><div><span class="wl-word">'+escH(w.word)+'</span>'+(w.phonetic?'<span class="wl-ph">'+escH(w.phonetic)+'</span>':'')+'<div class="wl-mean">'+escH(w.meaning)+'</div></div><div class="wl-right">'+lv+'<button class="wl-del" onclick="delWord('+w.id+')">✕</button></div></div>'});area.innerHTML=h}
function delWord(id){if(!confirm("\u786E\u5B9A\u5220\u9664\uFF1F"))return;words=words.filter(function(w){return w.id!==id});saveWords();updateStats();renderList()}
function showAdd(){document.getElementById("addModal").classList.add("show");document.getElementById("inpWord").focus()}
function hideAdd(){document.getElementById("addModal").classList.remove("show");["inpWord","inpPhonetic","inpMeaning","inpSent1","inpSent2"].forEach(function(id){document.getElementById(id).value=""})}
function submitAdd(){var w=document.getElementById("inpWord").value.trim().toLowerCase();var p=document.getElementById("inpPhonetic").value.trim();var m=document.getElementById("inpMeaning").value.trim();var s1=document.getElementById("inpSent1").value.trim();var s2=document.getElementById("inpSent2").value.trim();if(!w||!m||!s1){alert("\u8BF7\u81F3\u5C11\u586B\u5199\u5355\u8BCD\u3001\u91CA\u4E49\u548C\u4F8B\u53E5");return}function fix(s){if(s&&!s.includes("{{"))s=s.replace(new RegExp("\\b"+escRe(w)+"\\b","i"),"{{"+w+"}}");return s}var sa=[];if(s1)sa.push(fix(s1));if(s2)sa.push(fix(s2));words.push(mkW(w,p,m,sa));saveWords();updateStats();hideAdd();renderList();goPage("list",document.querySelectorAll(".nav-item")[2])}
function showImport(){document.getElementById("importModal").classList.add("show");document.getElementById("importArea").focus();document.getElementById("importMsg").className="import-msg";document.getElementById("importArea").value=""}
function hideImport(){document.getElementById("importModal").classList.remove("show")}
function doImport(){var raw=document.getElementById("importArea").value.trim();var msg=document.getElementById("importMsg");if(!raw){msg.className="import-msg err";msg.textContent="\u8BF7\u7C98\u8D34\u5355\u8BCD\u6570\u636E";return}var lines=raw.split("\n").map(function(l){return l.trim()}).filter(function(l){return l});var count=0,errs=[];lines.forEach(function(line,li){var parts=line.split("|").map(function(p){return p.trim()}).filter(function(p){return p});if(parts.length<3){errs.push("\u7B2C"+(li+1)+"\u884C\u683C\u5F0F\u4E0D\u6B63\u786E");return}var w=parts[0].toLowerCase(),m=parts[1],sa=[];for(var i=2;i<parts.length;i++){var s=parts[i];if(s&&!s.includes("{{"))s=s.replace(new RegExp("\\b"+escRe(w)+"\\b","i"),"{{"+w+"}}");if(s)sa.push(s)}if(!w||!m||sa.length===0){errs.push("\u7B2C"+(li+1)+"\u884C\u7F3A\u5C11\u5FC5\u8981\u4FE1\u606F");return}words.push(mkW(w,"",m,sa));count++});saveWords();updateStats();if(errs.length>0){msg.className="import-msg err";msg.textContent="\u6210\u529F\u5BFC\u5165 "+count+" \u4E2A\uFF0C\u5931\u8D25 "+errs.length+" \u4E2A\u3002"+(errs[0]||"")}else{msg.className="import-msg ok";msg.textContent="\u2705 \u6210\u529F\u5BFC\u5165 "+count+" \u4E2A\u5355\u8BCD\uFF01";setTimeout(function(){hideImport();renderList();goPage("list",document.querySelectorAll(".nav-item")[2])},800)}}
function renderReview(){document.getElementById("reviewNum").textContent=getDue().length;renderCal()}
function renderCal(){var area=document.getElementById("calArea"),dns=["\u65E5","\u4E00","\u4E8C","\u4E09","\u56DB","\u4E94","\u516D"],base=new Date();var h='<div class="cal-title">\uD83D\uDCC5 \u5B66\u4E60\u8BB0\u5F55</div><div class="cal-grid">';dns.forEach(function(d){h+='<div class="cal-hdr">'+d+'</div>'});for(var i=27;i>=0;i--){var d=new Date(base);d.setDate(d.getDate()-i);var ds=d.toISOString().split("T")[0];var log=JSON.parse(localStorage.getItem("vl_log_"+ds)||"[]");var cls="cal-day"+(log.length>0?" done":"")+(ds===today()?" today":"");h+='<div class="'+cls+'">'+d.getDate()+'</div>'}h+="</div>";area.innerHTML=h}
function startReview(){goPage("card",document.querySelectorAll(".nav-item")[0])}
function speak(text){if(!("speechSynthesis"in window))return;window.speechSynthesis.cancel();var u=new SpeechSynthesisUtterance(text);u.lang="en-US";u.rate=0.82;window.speechSynthesis.speak(u)}
document.addEventListener("keydown",function(e){if(document.getElementById("addModal").classList.contains("show")){if(e.key==="Escape")hideAdd();if(e.key==="Enter"&&e.ctrlKey)submitAdd();return}if(document.getElementById("importModal").classList.contains("show")){if(e.key==="Escape")hideImport();return}if(e.key===" "||e.key==="Enter"){e.preventDefault();if(!showingAnswer)flipCard()}if(e.key==="ArrowLeft"||e.key==="a"){e.preventDefault();judge(false)}if(e.key==="ArrowRight"||e.key==="d"){e.preventDefault();judge(true)}if(e.key==="n"&&showingAnswer)nextSent()});
updateStats();renderCard();
