var BUILTIN=[
  {w:"achieve",p:"/əˈtʃiːv/",m:"raggiungere, realizzare",s:["She finally {{achieve}}d her dream of becoming a doctor.", "The team {{achieve}}d excellent results this year."]},
  {w:"afford",p:"/əˈfɔːd/",m:"potersi permettere",s:["I can't {{afford}} a new phone right now.", "They finally {{afford}}ed to buy a house."]},
  {w:"agree",p:"/əˈɡriː/",m:"essere d'accordo",s:["I {{agree}} with your opinion completely.", "They finally {{agree}}d on the price."]},
  {w:"allow",p:"/əˈlaʊ/",m:"permettere",s:["My parents don't {{allow}} me to stay out late.", "The law does not {{allow}} parking here."]},
  {w:"argue",p:"/ˈɑːɡjuː/",m:"discutere",s:["They often {{argue}} about money.", "She {{argue}}d that education should be free."]},
  {w:"arrange",p:"/əˈreɪndʒ/",m:"organizzare",s:["Can you {{arrange}} a meeting for tomorrow?", "I need to {{arrange}} my books by color."]},
  {w:"arrive",p:"/əˈraɪv/",m:"arrivare",s:["We finally {{arrive}}d at the hotel at midnight.", "The package will {{arrive}} tomorrow morning."]},
  {w:"attend",p:"/əˈtend/",m:"partecipare",s:["Everyone should {{attend}} the meeting.", "She {{attend}}ed the same school as me."]},
  {w:"avoid",p:"/əˈvɔɪd/",m:"evitare",s:["You should {{avoid}} eating too much sugar.", "He tried to {{avoid}} answering the question."]},
  {w:"believe",p:"/bɪˈliːv/",m:"credere",s:["I {{believe}} that honesty is very important.", "Nobody wanted to {{believe}} her story."]},
  {w:"borrow",p:"/ˈbɒrəʊ/",m:"prendere in prestito",s:["Can I {{borrow}} your pen for a moment?", "She often {{borrow}}s books from the library."]},
  {w:"bother",p:"/ˈbɒðə/",m:"disturbare",s:["Don't {{bother}} cooking - we can order pizza.", "He didn't {{bother}} to lock the door."]},
  {w:"break",p:"/breɪk/",m:"rompere",s:["Be careful not to {{break}} the glass.", "Let's take a short {{break}} before continuing."]},
  {w:"breath",p:"/breθ/",m:"respiro",s:["Take a deep {{breath}} and relax.", "He was out of {{breath}} after running."]},
  {w:"build",p:"/bɪld/",m:"costruire",s:["They plan to {{build}} a new school here.", "She has {{build}}t a successful business."]},
  {w:"burn",p:"/bɜːn/",m:"bruciare",s:["The fire {{burn}}ed for several hours.", "Be careful not to {{burn}} your hand."]},
  {w:"calm",p:"/kɑːm/",m:"calmo, tranquillo",s:["Please try to stay {{calm}} during the exam.", "The sea was very {{calm}} that morning."]},
  {w:"cause",p:"/kɔːz/",m:"causa, provocare",s:["What was the {{cause}} of the accident?", "The heavy rain {{cause}}d a flood."]},
  {w:"challenge",p:"/ˈtʃælɪndʒ/",m:"sfida",s:["Climbing the mountain was a real {{challenge}}.", "She {{challenge}}d herself to run every day."]},
  {w:"change",p:"/tʃeɪndʒ/",m:"cambiare",s:["The weather can {{change}} very quickly here.", "Can you give me {{change}} for a 20 euro note?"]},
  {w:"check",p:"/tʃek/",m:"controllare",s:["Please {{check}} your email when you have time.", "I always {{check}} the door is locked."]},
  {w:"choose",p:"/tʃuːz/",m:"scegliere",s:["You can {{choose}} any color you like.", "It's difficult to {{choose}} between the two options."]},
  {w:"collect",p:"/kəˈlekt/",m:"raccogliere",s:["She loves to {{collect}} old postcards.", "Can you {{collect}} the kids from school?"]},
  {w:"communicate",p:"/kəˈmjuːnɪkeɪt/",m:"comunicare",s:["We use email to {{communicate}} with clients.", "Babies {{communicate}} by crying and smiling."]},
  {w:"compare",p:"/kəmˈpeə/",m:"confrontare",s:["It's hard to {{compare}} the two cities.", "Please {{compare}} these two options carefully."]},
  {w:"compete",p:"/kəmˈpiːt/",m:"gareggiare",s:["Five teams will {{compete}} in the finals.", "She loves to {{compete}} in chess tournaments."]},
  {w:"complain",p:"/kəmˈpleɪn/",m:"lamentarsi",s:["He always {{complain}}s about the weather.", "You should {{complain}} to the manager."]},
  {w:"concentrate",p:"/ˈkɒnsəntreɪt/",m:"concentrarsi",s:["I can't {{concentrate}} with all this noise.", "Please {{concentrate}} on one task at a time."]},
  {w:"confident",p:"/ˈkɒnfɪdənt/",m:"sicuro di se",s:["She felt {{confident}} before the interview.", "He gave a {{confident}} and clear speech."]},
  {w:"consider",p:"/kənˈsɪdə/",m:"considerare",s:["Please {{consider}} my suggestion carefully.", "I {{consider}} him one of my closest friends."]},
  {w:"continue",p:"/kənˈtɪnjuː/",m:"continuare",s:["The rain will {{continue}} until tomorrow.", "Please {{continue}} working on the project."]},
  {w:"control",p:"/kənˈtrəʊl/",m:"controllare",s:["He couldn't {{control}} his anger.", "The remote {{control}} is on the table."]},
  {w:"courage",p:"/ˈkʌrɪdʒ/",m:"coraggio",s:["It takes a lot of {{courage}} to speak in public.", "She had the {{courage}} to start a new life abroad."]},
  {w:"curious",p:"/ˈkjʊəriəs/",m:"curioso",s:["I'm very {{curious}} about other cultures.", "The cat was {{curious}} about the box."]},
  {w:"decide",p:"/dɪˈsaɪd/",m:"decidere",s:["We need to {{decide}} by tomorrow morning.", "She {{decide}}d to study abroad next year."]},
  {w:"defend",p:"/dɪˈfend/",m:"difendere",s:["Soldiers are trained to {{defend}} their country.", "She tried to {{defend}} her point of view."]},
  {w:"deliver",p:"/dɪˈlɪvə/",m:"consegnare",s:["The pizza will be {{deliver}}ed in 30 minutes.", "She {{deliver}}ed an excellent speech."]},
  {w:"depend",p:"/dɪˈpend/",m:"dipendere",s:["The result will {{depend}} on the weather.", "You can {{depend}} on me to help you."]},
  {w:"describe",p:"/dɪˈskraɪb/",m:"descrivere",s:["Can you {{describe}} the person you saw?", "She {{describe}}d the scene in detail."]},
  {w:"develop",p:"/dɪˈveləp/",m:"sviluppare",s:["Children {{develop}} at different speeds.", "The company plans to {{develop}} a new app."]},
  {w:"discuss",p:"/dɪsˈkʌs/",m:"discutere",s:["We need to {{discuss}} this issue together.", "They {{discuss}}ed the plan for two hours."]},
  {w:"distance",p:"/ˈdɪstəns/",m:"distanza",s:["The {{distance}} from here to the station is 2 km.", "We walked a long {{distance}} today."]},
  {w:"disturb",p:"/dɪˈstɜːb/",m:"disturbare",s:["Please don't {{disturb}} me while I'm studying.", "I'm sorry to {{disturb}} you, but it's urgent."]},
  {w:"divide",p:"/dɪˈvaɪd/",m:"dividere",s:["Let's {{divide}} the cake into eight pieces.", "The river {{divide}}s the city in two."]},
  {w:"double",p:"/ˈdʌbl/",m:"doppio, raddoppiare",s:["I'd like a {{double}} espresso, please.", "The price has {{double}}d in the last year."]},
  {w:"doubt",p:"/daʊt/",m:"dubbio",s:["I have no {{doubt}} that she will succeed.", "They {{doubt}}ed his ability to finish on time."]},
  {w:"education",p:"/ˌedʒuˈkeɪʃn/",m:"istruzione",s:["Education is very important for a country's future.", "She works in higher education."]},
  {w:"effect",p:"/ɪˈfekt/",m:"effetto",s:["The medicine had an immediate {{effect}}.", "Global warming will have a serious {{effect}}."]},
  {w:"effort",p:"/ˈefət/",m:"sforzo",s:["Learning a language requires a lot of {{effort}}.", "He put a lot of {{effort}} into the project."]},
  {w:"encourage",p:"/ɪnˈkʌrɪdʒ/",m:"incoraggiare",s:["Parents should {{encourage}} their children to read.", "The coach always {{encourage}}d the team."]},
  {w:"energy",p:"/ˈenədʒi/",m:"energia",s:["She has so much {{energy}} in the morning.", "We need to save {{energy}} at home."]},
  {w:"enjoy",p:"/ɪnˈdʒɔɪ/",m:"godere",s:["I really {{enjoy}}ed the concert last night.", "We hope you {{enjoy}} your stay here."]},
  {w:"enough",p:"/ɪˈnʌf/",m:"abbastanza",s:["Do we have {{enough}} time to finish?", "I haven't had {{enough}} sleep lately."]},
  {w:"ensure",p:"/ɪnˈʃʊə/",m:"garantire",s:["Please {{ensure}} that all doors are locked.", "This will {{ensure}} a better result."]},
  {w:"entire",p:"/ɪnˈtaɪə/",m:"intero, completo",s:["The entire project took three years.", "She spent the {{entire}} day reading."]},
  {w:"environment",p:"/ɪnˈvaɪrənmənt/",m:"ambiente",s:["We need to protect the natural {{environment}}.", "The office is a friendly working {{environment}}."]},
  {w:"escape",p:"/ɪˈskeɪp/",m:"fuggire",s:["They managed to {{escape}} from the burning building.", "Reading is a good {{escape}} from reality."]},
  {w:"establish",p:"/ɪˈstæblɪʃ/",m:"stabilire",s:["The company was {{establish}}ed in 1990.", "We need to {{establish}} a new policy."]},
  {w:"evidence",p:"/ˈevɪdəns/",m:"prova",s:["There is no {{evidence}} that he was involved.", "The police found {{evidence}} at the scene."]},
  {w:"exact",p:"/ɪɡˈzækt/",m:"esatto, preciso",s:["What is the {{exact}} time of the meeting?", "The two words have the {{exact}} same meaning."]},
  {w:"examine",p:"/ɪɡˈzæmɪn/",m:"esaminare",s:["The doctor will {{examine}} you carefully.", "We need to {{examine}} the data more closely."]},
  {w:"example",p:"/ɪɡˈzɑːmpl/",m:"esempio",s:["Can you give me an {{example}} of this grammar rule?", "For {{example}}, we could leave at 8 o'clock."]},
  {w:"excellent",p:"/ˈeksələnt/",m:"eccellente",s:["She did an {{excellent}} job on the presentation.", "The food at that restaurant is {{excellent}}."]},
  {w:"exist",p:"/ɪɡˈzɪst/",m:"esistere",s:["Do you think aliens {{exist}}?", "The problem doesn{{exist}}."]},
  {w:"expect",p:"/ɪkˈspekt/",m:"aspettarsi",s:["I {{expect}} to finish the report by Friday.", "Don't {{expect}} too much too soon."]},
  {w:"experience",p:"/ɪkˈspɪriəns/",m:"esperienza",s:["She has a lot of teaching {{experience}}.", "Living abroad was an amazing {{experience}}."]},
  {w:"explain",p:"/ɪkˈspleɪn/",m:"spiegare",s:["Can you please {{explain}} this rule to me?", "He didn't {{explain}} why he was late."]},
  {w:"explore",p:"/ɪkˈsplɔː/",m:"esplorare",s:["We want to {{explore}} the old part of the city.", "The children love to {{explore}} the garden."]},
  {w:"express",p:"/ɪkˈspres/",m:"esprimere",s:["She found it hard to {{express}} her feelings.", "Please {{express}} your opinion clearly."]},
  {w:"familiar",p:"/fəˈmɪliə/",m:"familiare",s:["The song sounds very {{familiar}}.", "Are you {{familiar}} with this software?"]},
  {w:"famous",p:"/ˈfeɪməs/",m:"famoso",s:["Paris is {{famous}} for the Eiffel Tower.", "She became {{famous}} after her first film."]},
  {w:"fear",p:"/fɪə/",m:"paura",s:["She has a {{fear}} of flying.", "There is no {{fear}} of losing the match."]},
  {w:"figure",p:"/ˈfɪɡə/",m:"figura, capire",s:["She's a well-known public {{figure}}.", "Can you {{figure}} out how to solve this?"]},
  {w:"focus",p:"/ˈfəʊkəs/",m:"concentrarsi",s:["You need to {{focus}} on your studies.", "The {{focus}} of the lesson is grammar."]},
  {w:"follow",p:"/ˈfɒləʊ/",m:"seguire",s:["Please {{follow}} the instructions carefully.", "She {{follow}}ed him to the station."]},
  {w:"foreign",p:"/ˈfɒrɪn/",m:"straniero",s:["He works in a {{foreign}} company.", "Do you speak any {{foreign}} languages?"]},
  {w:"frequent",p:"/ˈfriːkwənt/",m:"frequente",s:["He is a {{frequent}} visitor to this cafe.", "The most {{frequent}} problem is the internet connection."]},
  {w:"generation",p:"/ˌdʒenəˈreɪʃn/",m:"generazione",s:["Younger generations use technology more.", "This is a multi-generation family business."]},
  {w:"goal",p:"/ɡəʊl/",m:"obiettivo",s:["Our main {{goal}} is to improve customer service.", "She scored the winning {{goal}}."]},
  {w:"government",p:"/ˈɡʌvənmənt/",m:"governo",s:["The {{government}} introduced a new tax policy.", "People are losing trust in the {{government}}."]},
  {w:"gradual",p:"/ˈɡrædʒuəl/",m:"graduale",s:["There has been a {{gradual}} increase in sales.", "Learning takes {{gradual}} progress."]},
  {w:"guess",p:"/ɡes/",m:"indovinare",s:["Can you {{guess}} how old she is?", "I {{guess}} it will rain later."]},
  {w:"guide",p:"/ɡaɪd/",m:"guida",s:["Our tour {{guide}} spoke excellent English.", "This book is a helpful {{guide}} for beginners."]},
  {w:"harm",p:"/hɑːm/",m:"danno",s:["Pollution can {{harm}} the environment.", "He meant no {{harm}} by his comment."]},
  {w:"heart",p:"/hɑːt/",m:"cuore",s:["She has a very kind {{heart}}.", "He had a {{heart}} attack last year."]},
  {w:"heavy",p:"/ˈhevi/",m:"pesante",s:["It's going to rain - the sky looks very {{heavy}}.", "How {{heavy}} is this suitcase?"]},
  {w:"height",p:"/haɪt/",m:"altezza",s:["What is the {{height}} of Mount Everest?", "She is medium {{height}} and has dark hair."]},
  {w:"honest",p:"/ˈɒnɪst/",m:"onesto",s:["I think he is a very {{honest}} person.", "To be {{honest}}, I don't like this film."]},
  {w:"imagine",p:"/ɪˈmædʒɪn/",m:"immaginare",s:["Can you {{imagine}} life without a smartphone?", "I can't {{imagine}} how she managed alone."]},
  {w:"improve",p:"/ɪmˈpruːv/",m:"migliorare",s:["We need to {{improve}} our customer service.", "Her English has {{improve}}d a great deal."]},
  {w:"include",p:"/ɪnˈkluːd/",m:"includere",s:["The price does not {{include}} tax.", "The package {{include}}s free delivery."]},
  {w:"increase",p:"/ɪnˈkriːs/",m:"aumentare",s:["The city's population continues to {{increase}}.", "Exercise can {{increase}} your energy levels."]},
  {w:"influence",p:"/ˈɪnfluəns/",m:"influenza",s:["Social media has a huge {{influence}} on young people.", "His father {{influence}}d him a lot."]},
  {w:"manage",p:"/ˈmænɪdʒ/",m:"gestire, riuscire",s:["She {{manage}}s a team of twenty people.", "How do you {{manage}} to stay so calm?"]},
  {w:"necessary",p:"/ˈnesəsəri/",m:"necessario",s:["It's {{necessary}} to wear a seatbelt.", "Is it {{necessary}} to book in advance?"]},
  {w:"opinion",p:"/əˈpɪnjən/",m:"opinione",s:["In my {{opinion}}, this is the best option.", "Everyone is entitled to their own {{opinion}}."]},
  {w:"opportunity",p:"/ˌɒpəˈtjuːnəti/",m:"opportunità",s:["This is a great {{opportunity}} for you.", "Don't miss this {{opportunity}} to grow."]},
  {w:"participate",p:"/pɑːˈtɪsɪpeɪt/",m:"partecipare",s:["Everyone is welcome to {{participate}}.", "She refused to {{participate}} in the debate."]},
  {w:"persuade",p:"/pəˈsweɪd/",m:"convincere",s:["I finally {{persuade}}d him to see a doctor.", "Can anyone {{persuade}} her to change her mind?"]},
  {w:"prefer",p:"/prɪˈfɜː/",m:"preferire",s:["I {{prefer}} tea to coffee in the morning.", "Which do you {{prefer}}, red or blue?"]},
  {w:"prepare",p:"/prɪˈpeə/",m:"preparare",s:["We need to {{prepare}} for bad weather.", "She is {{prepare}}ing hard for her final exam."]},
  {w:"prevent",p:"/prɪˈvent/",m:"prevenire",s:["This vaccine can {{prevent}} serious illness.", "Nothing could {{prevent}} them from trying again."]},
  {w:"private",p:"/ˈpraɪvət/",m:"privato",s:["This is a {{private}} conversation.", "She goes to a {{private}} school."]},
  {w:"probably",p:"/ˈprɒbəbli/",m:"probabilmente",s:["It will {{probably}} rain tomorrow.", "He {{probably}} won't come to the party."]},
  {w:"promise",p:"/ˈprɒmɪs/",m:"promettere",s:["I {{promise}} I will call you tomorrow.", "The forecast {{promise}}s sunny weather this weekend."]},
  {w:"protect",p:"/prəˈtekt/",m:"proteggere",s:["We must {{protect}} the environment.", "Sunscreen {{protect}}s your skin from UV rays."]},
  {w:"provide",p:"/prəˈvaɪd/",m:"fornire",s:["The school will {{provide}} lunch for all students.", "Can you {{provide}} more details about the plan?"]},
  {w:"purpose",p:"/ˈpɜːpəs/",m:"scopo",s:["What is the {{purpose}} of this meeting?", "She studied medicine with a clear {{purpose}}."]},
  {w:"recognize",p:"/ˈrekəɡnaɪz/",m:"riconoscere",s:["I didn't {{recognize}} you with your new haircut!", "The government {{recognize}}d their contribution."]},
  {w:"recommend",p:"/ˌrekəˈmend/",m:"raccomandare",s:["Can you {{recommend}} a good restaurant nearby?", "I {{recommend}} reading this book to everyone."]},
  {w:"reduce",p:"/rɪˈdjuːs/",m:"ridurre",s:["We need to {{reduce}} our daily expenses.", "The company decided to {{reduce}} the price."]},
  {w:"regular",p:"/ˈreɡjʊlə/",m:"regolare",s:["He goes to the gym on a {{regular}} basis.", "This is a {{regular}} event in our school."]},
  {w:"require",p:"/rɪˈkwaɪə/",m:"richiedere",s:["The job {{require}}s a university degree.", "All visitors are {{require}}d to sign in."]},
  {w:"research",p:"/rɪˈsɜːtʃ/",m:"ricerca",s:["She is doing {{research}} on climate change.", "The {{research}} shows interesting results."]},
  {w:"responsible",p:"/rɪˈspɒnsɪbl/",m:"responsabile",s:["Who is {{responsible}} for this project?", "She is a very {{responsible}} person."]},
  {w:"satisfy",p:"/ˈsætɪsfaɪ/",m:"soddisfare",s:["The results didn't fully {{satisfy}} him.", "Nothing seems to {{satisfy}} her curiosity."]},
  {w:"solution",p:"/səˈluːʃn/",m:"soluzione",s:["We need to find a {{solution}} to this problem.", "There is no simple {{solution}} to this issue."]},
  {w:"suffer",p:"/ˈsʌfə/",m:"soffrire",s:["Many people {{suffer}} from stress at work.", "The town {{suffer}}ed heavy damage in the storm."]},
  {w:"support",p:"/səˈpɔːt/",m:"supportare",s:["Thank you for {{support}}ing me through this.", "The government {{support}}s small businesses."]},
  {w:"survive",p:"/səˈvaɪv/",m:"sopravvivere",s:["He {{survive}}d the accident without serious injury.", "It's difficult to {{survive}} alone in the wild."]},
  {w:"suggest",p:"/səˈdʒest/",m:"suggerire",s:["I {{suggest}} we take a different route today.", "She {{suggest}}ed meeting at the coffee shop."]},
  {w:"value",p:"/ˈvæljuː/",m:"valore",s:["This painting has great historical {{value}}.", "I really {{value}} our friendship."]},
  {w:"volunteer",p:"/ˌvɒlənˈtɪə/",m:"volontario",s:["She works as a {{volunteer}} at the hospital.", "We need {{volunteer}}s for the charity event."]},
  {w:"wonder",p:"/ˈwʌndə/",m:"chiedersi",s:["I {{wonder}} what time the train leaves.", "She {{wonder}}ed if he would come to the party."]}
];
